---
- name: Ensure log folder exists and is writeable
  become: true
  ansible.builtin.file:
    path: "{{ restic_log_dir }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    mode: "0755"

- name: Ensure cache dir exists and is writeable
  become: true
  ansible.builtin.file:
    path: "{{ restic__cache_dir }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    mode: "0750"

- name: Set ownership recursively
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    recurse: true
  with_items:
    - "{{ restic_log_dir }}"
    - "{{ restic__cache_dir }}"
